language: java

sudo: false

before_install: wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh

install:
  - . ./install-jdk.sh -F 10 -L BCL
  - chmod a+x ./gradlew

cache:
  directories:
    - $HOME/.gradle

script: ./gradlew --info --stacktrace build
